### ISSUE TITLE
win7下载最新的软件邮件测试失败

### ISSUE THREAD

**Issue by yczhang11** [fate233/openwebmonitor#11]
![image](https://user-images.githubusercontent.com/40254214/47015769-72646000-d180-11e8-9a72-d7078ef8fd63.png)
![image](https://user-images.githubusercontent.com/40254214/47015789-80b27c00-d180-11e8-8710-f87cba8c6e7d.png)
完全按照教程来配置的还是测试失败

**Comment by fateleak** [comment]
服务器的后缀改成stmp.qq.com
下面的邮箱要有@qq.com
