### ISSUE TITLE
是否能监控贴吧回复

### ISSUE THREAD

**Issue by zhiyuan-zhang** [fate233/openwebmonitor#26]
我有几个小问题
1. 贴吧帖子回复能实现么? 
好像目前只能监控固定的量 动态的有点麻烦
虽然可以直接监控回复总数 
但问题又来了 
当我监控到回复总数+1后
我能不能直接get到回复内容发送过来呢

**Comment by fate233** [comment]
总数变了能发现，get那个回复做不到的
